### ISSUE TITLE
Slider value becomes detached from nob

### ISSUE THREAD

**Issue by scothis** [mapbox/react-range#10] opened 2015-11-04 18:45 UTC
If you click on the slider nob and start dragging, then drag off the range, the nob will continue to move, but the updated value is not emitted.

We likely need to listen for mousemove and mouseup events globally when a mouse down is detected.

Tested in Safari 9.

**Comment by dspnorman** [comment] 2016-04-07 18:57
Duplicate of #13

**Comment by dasulit** [comment] 2019-01-24 16:08
Mapbox is no longer maintaining react-range. For a current alternative, check out https://mapbox.github.io/mr-ui/#controlrange.

**Closed as completed by dasulit** 2019-01-24 16:08 UTC
